apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-audit-log-scraper
  labels:
    app.kubernetes.io/name: cloudflare-audit-log-scraper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-audit-log-scraper
  endpoints:
    - port: metrics
