apiVersion: v1
kind: Service
metadata:
  name: cloudflare-audit-log-scraper
  labels:
    app.kubernetes.io/name: cloudflare-audit-log-scraper
spec:
  selector:
    app.kubernetes.io/name: cloudflare-audit-log-scraper
  ports:
    - name: metrics
      port: 2112
